name: minerl
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - py-opencv
  - cudatoolkit=10.2
  - pytorch=1.9.0
  - pip:
    - git+https://github.com/minerllabs/minerl
    - coloredlogs
    - matplotlib
    - gym3
    - attrs
